# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ygocard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_type', to='ygocard.CardType'),
        ),
    ]
